/*
 * pmic.c
 *
 *  Created on: Jan 5, 2016
 *      Author: Myant
 */

#include "tskctrl.h"
#include "FreeRTOS.h"
#include "task.h"
#include "logger.h"
#include "logio.h"
#include "mya_util.h"
#include "pmic.h"
#include "tps65987.h"
#include "hal_i2c.h"
#include "hal_gpio.h"
#include "ble_rpc.h"
#include "diagnostic.h"
#include "wdt.h"
#include "heat_ctrl.h"

#if PCB_ID == PCB_MULTI_CHANNEL

//if battery % is below this value, enter ship mode
#define BATT_OFF 		0
static uint8_t batt_range=0;
static uint16_t batt_level=0;
static wdt_entry wdt = NULL;
static TaskHandle_t tskhnd = NULL;

static void tsk_pmic_wdt(void *params);

static void tsk_pmic_wdt(void *params)
{
    uint8_t range;
    uint16_t level;
    pmic_status_t pmicst;

    while(1)
    {
    	//<<hack>> event EVT_HEATING_OFF needs to be generated by other module
		os_evt_wait(EVT_HEATING_OFF, WAIT_FOREVER);//wait for heating off for measurement  /* Note: Check why heating needs to be off power measurement? */
		wdt_unblock_task(wdt);
		pmicst = tps_read_batt_range(&range);
        pmicst |= tps_read_batt_level(&level);
        if(PMICST_OK == pmicst)
        {
        	batt_level=level;
        	batt_range=range;
        }
        wdt_feed(wdt);
    }
}

uint8_t pmic_get_battery_range(void)
{
	return batt_range;
}

uint16_t pmic_get_battery_level(void)
{
    return batt_level;
}

bool pmic_init(void)
{
    pmic_status_t st;
    st = tps_init();
    if(PMICST_OK != st)
    {
    	diag_inc_flag(FLG_PMIC_INIT);
        log_error("[pmic] failed to initialize: %d", st);
        return false;
    }
    else
    {
    	tps_neg_contract(DEFAULT_VOLTAGE);//set default voltage:5v
    	tps_read_batt_range(&batt_range);
    	tps_read_batt_level(&batt_level);
       	tskhnd = tsk_create(TSK_PMIC_WDT, tsk_pmic_wdt);
		ASSERT_TASK(tskhnd);
		//config watchdog timer
		wdt_config_t wconfig;
		wconfig.id = TSK_PMIC_WDT;
		wconfig.enabled = true;
		wconfig.event_mask = 0;
		//when heating is off, mearsure battery and temperature every 3s
		wconfig.timeout = 2;
		wconfig.type = WDT_E_BLOCKING;
		wdt = wdt_config_entry(&wconfig, pdMS_TO_TICKS(200));
		log_info("[pmic] initialized");
    }
    return true;
}
#elif PCB_ID == PCB_DUAL_CHANNEL
bool pmic_init(void)
{
	hal_gpio_set(V_HEATER_EN);
	return true;
}

uint8_t  pmic_get_battery_range(void) {return 30;} //<<hack>> to avoid blinking red (low battery)
uint16_t pmic_get_battery_level(void) {return 0;}
#endif
